### ISSUE TITLE
Support for all screen sizes

### ISSUE THREAD

**Issue by gingerbeardman** [matbroughty/timstwitterlisteningparty#1]
I noticed that this looks odd on:
1. mobile
- should ideally not need horizontal scrolling

2. narrow desktop screens
- side bar issue
![Screen shot 2020-03-30 at 11 51 20](https://user-images.githubusercontent.com/49612/77905005-6b021b00-727d-11ea-9c30-ff6416d816fd.png)

**Comment by matbroughty** [comment]
These have been resolved now so closing!
