### ISSUE TITLE
GitHub Discussions?

### ISSUE THREAD

**Issue by BenNeighbour** [matbroughty/timstwitterlisteningparty#17]
Hi @matbroughty @gingerbeardman @johnruane @ajbrindle, unless there is already a Discord Server/MS Teams chat for this 
project, then maybe you should consider creating a GitHub Discussion (a newer feature) which allows you to have discussions as another tab on this GitHub Repo. Then that way it would be better/easier for newer contributes to get on-board. Hopefully this suggestion helps - I'm sorry if I'm just being annoying!

[Here's how to create a Discussion](https://docs.github.com/en/discussions/quickstart)

Cheers, Ben 👍

**Comment by gingerbeardman** [comment]
We have multiple Twitter group DMs to manage this, keeping everything Twitter so Tim can be involved. Email or any other method was refused. ;)
