### ISSUE TITLE
Past events make more sense to be listed most recent first?

### ISSUE THREAD

**Issue by gingerbeardman** [matbroughty/timstwitterlisteningparty#2]

**Comment by matbroughty** [comment]
The thinking was the top of the page would have this weeks listening and as each went past they would be moved to the bottom.  So current and upcoming at top and history at the bottom.

**Comment by gingerbeardman** [comment]
Given that these are now on their own page, there order no longer bothers me! 😆

**Comment by matbroughty** [comment]
And I have fixed it now as well!
